### PR TITLE
Change Behavior of While to More Closely Match TextMate

### LINKED ISSUE #25: Fix While Behavior to Match TextMate
Following up on #24, I still don't think we handle `while` rules correctly.

Here's a toy TextMate grammar I've been using to test this:

```js
{	patterns = (
		{	include = '#alist'; },
		{	include = '#blist'; },
	);
	repository = {
		alist = {
			name = 'alist';
			begin = 'A';
			while = 'a';
			patterns = (
				{	include = '#alist'; },
				{	include = '#blist'; },
				{	include = '#letter'; },
			);
		};
		letter = {
			name = 'constant.language.json';
			match = 'x';
		};
		blist = {
			name = 'blist';
			begin = 'B';
			while = 'b';
			patterns = (
				{	include = '#alist'; },
				{	include = '#blist'; },
				{	include = '#number'; },
			);
		};
		number = {
			name = 'constant.numeric.json';
			match = '\d';
		};
	};
}
```

After using this grammar in TextMate, I believe the behavior of `while` is actually:

1. On a new line, check all while conditions from bottom of the stack to the top.
2. If any of them fails, then pop everything after that while rule off the stack, along with the failed rule.

`while` is not documented anywhere as far as I could find. This behavior also differs from other productions, but all this does make some sense for the markdown grammar at least. 

Here's a few samples that show these behaviors:

```
A 1x
a B 1x
ab 1x
b 1x
a 1x

A 1x
a B 1x
ab 1x
a 1x
b 1x

A 1x
a B 1x
ba 1x
a 1x
b 1x

A 1x
a B 1x
bab 1x
a 1x
b 1x
```

screen shot 2016-09-22 at 7 36 10 pm

Comparing the second and third examples, the only difference is the swap of `ab` to `ba` on the third line. In the `ba` case, we see that the `alist`  `while` must be run first because it matches the `a` in the string. `blist` `while` is then checked, but there is no `b` after the `a` so it fails.

A few other points to consider:

* `while` checks can consume text. This is required for properly parsing indented lists in markdown.
* `while` checks run from the beginning of the line, or from wherever the last `while` check consumed up to.
* But `while` does not have to match starting at beginning of the line. It can match anywhere in the line. This is shown in the third example with `bab 1x` The outermost `alist` starts matching from the second character.

I'm putting together some test cases for this behavior and will try getting together a PR sometime next week.

### PR DESCRIPTION
**Pull request by mjbvz**
Updates while rule conditions to be run once for each new line, from bottom of the stack to the top of the stack. See #25 for more details. This matches what I believe text mate does.

Closes #25

### CODE REVIEW

**Comment by alexandrudima** [comment]
@mjbvz @kieferrm Is this something we want to ship in September? (or can it wait?)

**Comment by kieferrm** [comment]
@alexandrudima we are currently testing.

**Comment by mjbvz** [comment]
Testing in VS code itself. The only break I've seen so far is with blockquotes in markdown.

I also realized that we don't handle captures inside the while expression itself. This is required in blockquotes for example, so that we mark the starting `>` differently. The only reason I can tell that block quotes currently are tokenized correctly is that each line is parsed individually. But this prevents code like

```md
> ```js
> console.log("hello");
> ```
````

From getting tokenized.

I've got a local fix for the main block quote issue and will update the PR shortly. I'll also look into the captures fix. I think that text mate uses the same captures block for both the `begin` and `while` in a rule: https://github.com/textmate/markdown.tmbundle/blob/master/Syntaxes/Markdown.tmLanguage#L68

**Comment by mjbvz** [comment]
@alexandrudima I just talked with @kieferrm and we agreed that we don't want to take this change into the September release. Even after running the changes against a few markdown test suites, I don't have enough confidence that this won't break something for real world documents.

Instead, lets get this into the insiders vscode builds so that people can start using running it against their documents and report any edge case bugs we may have missed.

**Comment by alexandrudima** [comment]
@mjbvz 👍 To get it in the insiders release channel we're going to need to wait until master is open for business again (should be end of this week or beginning of next week)

**Comment by mjbvz** [comment]
@alexandrudima Now that 1.6 has branched off master, can you please take a look at this PR. Once it's merged in, I can handle updating the dependency on the VS Code side.

**Comment by alexandrudima** [comment]
@mjbvz Thank you, LGTM. I will publish a new version of vscode-textmate with this change in, I leave it to you to update the dependency in VS Code and adjust colorization tests, etc.

**Comment by alexandrudima** [comment]
@mjbvz vscode-textmate@2.3.0 now contains the change.

**Pull request merged**
