### PR TITLE
Allow empty or missing begin

### PR DESCRIPTION
**Pull request by msftrncs**
This addresses the other half of #82, by allowing a begin rule to be empty (or otherwise missing) as long as an end rule exists.

This PR was submitted separately so it can be considered separately.

I have only tested through the 'inspect' tool.

### CODE REVIEW

**Comment by msftrncs** [comment]
The errors in the CI seems to be from the fact that the JADE language uses the same constructs as the PUG language described in #82 and more fully described in https://github.com/Microsoft/vscode/issues/65983.  This causes the test to have fewer results than is expected, but I am not fully sure if the code is finding an empty 'canonicalTokens` element, or running out of elements.   It looks like the test for JADE will need amended, as the expected test results are incorrect.

**Comment by msftrncs** [comment]
#22 would appear to be the same issue, though its marked closed, I don't think it was ever remedied.

**Comment by alexandrudima** [comment]
:+1: Thank you!

**Comment by neilsoult** [comment]
Thanks guys, I am looking forward to the April release!

**Pull request merged**
