### PR TITLE
Implement `FontStyle.Strikethrough`

### PR DESCRIPTION
**Pull request by SNDST00M**
Writing tests for this might make us all a little ~~cross~~ (had to!)

Closes #159.

### CODE REVIEW

**Comment by alexdima** [comment]
I think we should also adjust https://github.com/microsoft/vscode-textmate/blob/d87b3d53fc9816f38d79342038b14d00f7e72bfa/src/grammar.ts#L23

**Comment by SNDST00M** [comment]
Alright will we be removing `MetaEmbedded` prop?

**Comment by alexdima** [comment]
No, `MetaEmbedded` is a temporary value that is never really encoded in a 32 bit integer. It becomes 'Other' right before being encoded [here](https://github.com/microsoft/vscode-textmate/blob/d87b3d53fc9816f38d79342038b14d00f7e72bfa/src/grammar.ts#L1255). I think the needed change is to [change `RegEx` from `4` to `3`](https://github.com/microsoft/vscode-textmate/blob/d87b3d53fc9816f38d79342038b14d00f7e72bfa/src/grammar.ts#L27).

**Comment by SNDST00M** [comment]
Oh right tests will need updating too

**Comment by alexdima** [comment]
Yes, looks like there's another `StandardTokenType` enum [here](https://github.com/microsoft/vscode-textmate/blob/d87b3d53fc9816f38d79342038b14d00f7e72bfa/src/main.ts#L59) where the `RegEx` needs to be changed to `3`.

**Comment by SNDST00M** [comment]
Huh it's passing nice

**Comment by alexdima** [comment]
Nice! Thank you!

**Pull request merged**
