### PR TITLE
Add grammar performance warning

### PR DESCRIPTION
**Pull request by Yanpas**
Inspired by https://github.com/microsoft/vscode/issues/92369

### CODE REVIEW

**Comment by Yanpas** [comment]
This code is executed in the browser context, so there is no need in perf_hooks module

**Comment by Yanpas** [comment]
1. I can use smth like `(performance as any)?.now()`. (Sadly this is not merged https://github.com/nodejs/node/issues/28635)
2. I think we can reuse `DebugFlags.InDebugMode`. It is enabled easily via VSCODE_TEXTMATE_DEBUG env.

**Comment by alexdima** [comment]
* `DebugFlags.InDebugMode` makes sense.
* `Date.now()` can be used everywhere.

**Comment by Yanpas** [comment]
`Date.now()` is unsuitable cause it's not monotonic. (You called Date.now, OS scheduler stopped the process, some other process did it's work (language server e.g.), now our process has CPU again and consecutive call Date.now will return all time that has passed in real life, not process's life.

So I see no other option as proposed above

**Comment by Yanpas** [comment]
Updated branch

**Comment by alexdima** [comment]
Thank you!

**Pull request merged**
